# Generated by Django 2.1 on 2018-08-21 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='things',
            name='dater_th',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='things',
            name='name_th',
            field=models.TextField(null=True, verbose_name='Nombre'),
        ),
    ]
